export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

export const CART_SAVE_SHIPPING_ADDRESSS = 'CART_SAVE_SHIPPING_ADDRESSS'

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

export const SET_DURATION_VALUES = 'SET_DURATION_VALUES';
export const SET_DURATION_INPUTS = 'SET_DURATION_INPUTS';
export const UPDATE_TOTAL_PRICE = 'UPDATE_TOTAL_PRICE';
export const UPDATE_SUBTOTAL = 'UPDATE_SUBTOTAL';
export const SET_AMT = 'SET_AMT';